/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-08-02 10:24:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fproductinsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/kimjunho/Desktop/littlePick/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/littlePick/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1626234805000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<!-- Basic Page Info -->\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<title>상품 관리 페이지</title>\n");
      out.write("\n");
      out.write("	<!-- Site favicon -->\n");
      out.write("	<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"resources/admin/resources/vendors/images/apple-touch-icon.png\">\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"resources/admin/resources/vendors/images/favicon-32x32.png\">\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"resources/admin/resources/vendors/images/favicon-16x16.png\">\n");
      out.write("\n");
      out.write("	<!-- Mobile Specific Metas -->\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("\n");
      out.write("	<!-- Google Font -->\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("	<!-- CSS -->\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/admin/resources/vendors/styles/core.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/admin/resources/vendors/styles/icon-font.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/admin/resources/plugins/datatables/css/dataTables.bootstrap4.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/admin/resources/plugins/datatables/css/responsive.bootstrap4.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/admin/resources/vendors/styles/style.css\">\n");
      out.write("\n");
      out.write("	<!-- Global site tag (gtag.js) - Google Analytics -->\n");
      out.write("	<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-119386393-1\"></script>\n");
      out.write("	<script>\n");
      out.write("		window.dataLayer = window.dataLayer || [];\n");
      out.write("		function gtag(){dataLayer.push(arguments);}\n");
      out.write("		gtag('js', new Date());\n");
      out.write("\n");
      out.write("		gtag('config', 'UA-119386393-1');\n");
      out.write("	</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"header\">\n");
      out.write("		<div class=\"header-left\">\n");
      out.write("			<div class=\"menu-icon dw dw-menu\"></div>\n");
      out.write("			<div class=\"search-toggle-icon dw dw-search2\" data-toggle=\"header_search\"></div>\n");
      out.write("			<div class=\"header-search\">\n");
      out.write("				<form>\n");
      out.write("					<div class=\"form-group mb-0\">\n");
      out.write("					<!--  \n");
      out.write("						<i class=\"dw dw-search2 search-icon\"></i>\n");
      out.write("						<input type=\"text\" class=\"form-control search-input\" placeholder=\"Search Here\">\n");
      out.write("						<div class=\"dropdown\">\n");
      out.write("							<a class=\"dropdown-toggle no-arrow\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\n");
      out.write("								<i class=\"ion-arrow-down-c\"></i>\n");
      out.write("							</a>\n");
      out.write("							<div class=\"dropdown-menu dropdown-menu-right\">\n");
      out.write("								<div class=\"form-group row\">\n");
      out.write("									<label class=\"col-sm-12 col-md-2 col-form-label\">From</label>\n");
      out.write("									<div class=\"col-sm-12 col-md-10\">\n");
      out.write("										<input class=\"form-control form-control-sm form-control-line\" type=\"text\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-group row\">\n");
      out.write("									<label class=\"col-sm-12 col-md-2 col-form-label\">To</label>\n");
      out.write("									<div class=\"col-sm-12 col-md-10\">\n");
      out.write("										<input class=\"form-control form-control-sm form-control-line\" type=\"text\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"form-group row\">\n");
      out.write("									<label class=\"col-sm-12 col-md-2 col-form-label\">Subject</label>\n");
      out.write("									<div class=\"col-sm-12 col-md-10\">\n");
      out.write("										<input class=\"form-control form-control-sm form-control-line\" type=\"text\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"text-right\">\n");
      out.write("									<button class=\"btn btn-primary\">Search</button>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						-->\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"header-right\">\n");
      out.write("			<div class=\"dashboard-setting user-notification\">\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a class=\"dropdown-toggle no-arrow\" href=\"resources/admin/resources/javascript:;\" data-toggle=\"right-sidebar\">\n");
      out.write("						<i class=\"dw dw-settings2\"></i>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!--  \n");
      out.write("			<div class=\"user-notification\">\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a class=\"dropdown-toggle no-arrow\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\n");
      out.write("						<i class=\"icon-copy dw dw-notification\"></i>\n");
      out.write("						<span class=\"badge notification-active\"></span>\n");
      out.write("					</a>\n");
      out.write("					<div class=\"dropdown-menu dropdown-menu-right\">\n");
      out.write("						<div class=\"notification-list mx-h-350 customscroll\">\n");
      out.write("							<ul>\n");
      out.write("								<li>\n");
      out.write("									<a href=\"#\">\n");
      out.write("										<img src=\"vendors/images/img.jpg\" alt=\"\">\n");
      out.write("										<h3>John Doe</h3>\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\n");
      out.write("									</a>\n");
      out.write("								</li>\n");
      out.write("								<li>\n");
      out.write("									<a href=\"#\">\n");
      out.write("										<img src=\"vendors/images/photo1.jpg\" alt=\"\">\n");
      out.write("										<h3>Lea R. Frith</h3>\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\n");
      out.write("									</a>\n");
      out.write("								</li>\n");
      out.write("								<li>\n");
      out.write("									<a href=\"#\">\n");
      out.write("										<img src=\"vendors/images/photo2.jpg\" alt=\"\">\n");
      out.write("										<h3>Erik L. Richards</h3>\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\n");
      out.write("									</a>\n");
      out.write("								</li>\n");
      out.write("								<li>\n");
      out.write("									<a href=\"#\">\n");
      out.write("										<img src=\"vendors/images/photo3.jpg\" alt=\"\">\n");
      out.write("										<h3>John Doe</h3>\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\n");
      out.write("									</a>\n");
      out.write("								</li>\n");
      out.write("								<li>\n");
      out.write("									<a href=\"#\">\n");
      out.write("										<img src=\"vendors/images/photo4.jpg\" alt=\"\">\n");
      out.write("										<h3>Renee I. Hansen</h3>\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\n");
      out.write("									</a>\n");
      out.write("								</li>\n");
      out.write("								<li>\n");
      out.write("									<a href=\"#\">\n");
      out.write("										<img src=\"vendors/images/img.jpg\" alt=\"\">\n");
      out.write("										<h3>Vicki M. Coleman</h3>\n");
      out.write("										<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed...</p>\n");
      out.write("									</a>\n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("			-->\n");
      out.write("			<div class=\"user-info-dropdown\">\n");
      out.write("				<div class=\"dropdown\">\n");
      out.write("					<a class=\"dropdown-toggle\" href=\"#\" role=\"button\" data-toggle=\"dropdown\">\n");
      out.write("						<span class=\"user-icon\">\n");
      out.write("							<img src=\"resources/admin/resources/images/LittlePickLogo.png\" alt=\"\">\n");
      out.write("						</span>\n");
      out.write("						<span class=\"user-name\">admin</span>\n");
      out.write("					</a>\n");
      out.write("					<div class=\"dropdown-menu dropdown-menu-right dropdown-menu-icon-list\">\n");
      out.write("						<a class=\"dropdown-item\" href=\"profile.html\"><i class=\"dw dw-user1\"></i> Profile</a>\n");
      out.write("						<a class=\"dropdown-item\" href=\"profile.html\"><i class=\"dw dw-settings2\"></i> Setting</a>\n");
      out.write("						<a class=\"dropdown-item\" href=\"faq.html\"><i class=\"dw dw-help\"></i> Help</a>\n");
      out.write("						<a class=\"dropdown-item\" href=\"login.html\"><i class=\"dw dw-logout\"></i> Log Out</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("<!-- ---------레이아웃 세팅-------------------------------------------------------------------------------------------------------- -->\n");
      out.write("	<div class=\"right-sidebar\">\n");
      out.write("		<div class=\"sidebar-title\">\n");
      out.write("			<h3 class=\"weight-600 font-16 text-blue\">\n");
      out.write("				레이아웃 세팅\n");
      out.write("				<span class=\"btn-block font-weight-400 font-12\">User Interface Settings</span>\n");
      out.write("			</h3>\n");
      out.write("			<div class=\"close-sidebar\" data-toggle=\"right-sidebar-close\">\n");
      out.write("				<i class=\"icon-copy ion-close-round\"></i>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"right-sidebar-body customscroll\">\n");
      out.write("			<div class=\"right-sidebar-body-content\">\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Header Background</h4>\n");
      out.write("				<div class=\"sidebar-btn-group pb-30 mb-10\">\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary header-white active\">White</a>\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary header-dark\">Dark</a>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Sidebar Background</h4>\n");
      out.write("				<div class=\"sidebar-btn-group pb-30 mb-10\">\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary sidebar-light \">White</a>\n");
      out.write("					<a href=\"javascript:void(0);\" class=\"btn btn-outline-primary sidebar-dark active\">Dark</a>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Menu Dropdown Icon</h4>\n");
      out.write("				<div class=\"sidebar-radio-group pb-10 mb-10\">\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebaricon-1\" name=\"menu-dropdown-icon\" class=\"custom-control-input\" value=\"icon-style-1\" checked=\"\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebaricon-1\"><i class=\"fa fa-angle-down\"></i></label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebaricon-2\" name=\"menu-dropdown-icon\" class=\"custom-control-input\" value=\"icon-style-2\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebaricon-2\"><i class=\"ion-plus-round\"></i></label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebaricon-3\" name=\"menu-dropdown-icon\" class=\"custom-control-input\" value=\"icon-style-3\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebaricon-3\"><i class=\"fa fa-angle-double-right\"></i></label>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<h4 class=\"weight-600 font-18 pb-10\">Menu List Icon</h4>\n");
      out.write("				<div class=\"sidebar-radio-group pb-30 mb-10\">\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-1\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-1\" checked=\"\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-1\"><i class=\"ion-minus-round\"></i></label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-2\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-2\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-2\"><i class=\"fa fa-circle-o\" aria-hidden=\"true\"></i></label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-3\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-3\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-3\"><i class=\"dw dw-check\"></i></label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-4\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-4\" checked=\"\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-4\"><i class=\"icon-copy dw dw-next-2\"></i></label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-5\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-5\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-5\"><i class=\"dw dw-fast-forward-1\"></i></label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("						<input type=\"radio\" id=\"sidebariconlist-6\" name=\"menu-list-icon\" class=\"custom-control-input\" value=\"icon-list-style-6\">\n");
      out.write("						<label class=\"custom-control-label\" for=\"sidebariconlist-6\"><i class=\"dw dw-next\"></i></label>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("\n");
      out.write("				<div class=\"reset-options pt-30 text-center\">\n");
      out.write("					<button class=\"btn btn-danger\" id=\"reset-settings\">Reset Settings</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("<!-- ----왼쪽 메뉴바------------------------------------------------------------------------------------------------------------- -->\n");
      out.write("	<div class=\"left-side-bar\">\n");
      out.write("		<div class=\"brand-logo\">\n");
      out.write("			<a href=\"index.html\">\n");
      out.write("				<img src=\"vendors/images/deskapp-logo.svg\" alt=\"\" class=\"dark-logo\">\n");
      out.write("				<img src=\"vendors/images/deskapp-logo-white.svg\" alt=\"\" class=\"light-logo\">\n");
      out.write("			</a>\n");
      out.write("			<div class=\"close-sidebar\" data-toggle=\"left-sidebar-close\">\n");
      out.write("				<i class=\"ion-close-round\"></i>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("				<div class=\"menu-block customscroll\">\n");
      out.write("			<div class=\"sidebar-menu\">\n");
      out.write("				<ul id=\"accordion-menu\">\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"main.do?smallpack=1\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-house-1\"></span><span class=\"mtext\">홈페이지 이동</span>\n");
      out.write("						</a>\n");
      out.write("					\n");
      out.write("					</li>\n");
      out.write("		  			\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"admin_member.do\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-library\"></span><span class=\"mtext\">회원 관리</span>\n");
      out.write("						</a>\n");
      out.write("						<!-- \n");
      out.write("						<ul class=\"submenu\">\n");
      out.write("							<li><a href=\"datatable.html\">회원 정보</a></li>\n");
      out.write("						</ul>\n");
      out.write("						 -->\n");
      out.write("					</li>\n");
      out.write("					\n");
      out.write("		\n");
      out.write("		<li class=\"dropdown\">\n");
      out.write("						<a href=\"admin_product.do\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-apartment\"></span><span class=\"mtext\"> 상품 관리 </span>\n");
      out.write("						</a>\n");
      out.write("						\n");
      out.write("					</li>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-edit2\"></span><span class=\"mtext\">문의사항 관리</span>\n");
      out.write("						</a>\n");
      out.write("						<ul class=\"submenu\">\n");
      out.write("							<li><a href=\"form-basic.html\">문의사항</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("\n");
      out.write("					\n");
      out.write("		<!--  			\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\n");
      out.write("							<span class=\"micon dw dw-paint-brush\"></span><span class=\"mtext\">Icons</span>\n");
      out.write("						</a>\n");
      out.write("						-->\n");
      out.write("		<!--  \n");
      out.write("						<ul class=\"submenu\">\n");
      out.write("							<li><a href=\"font-awesome.html\">FontAwesome Icons</a></li>\n");
      out.write("							<li><a href=\"foundation.html\">Foundation Icons</a></li>\n");
      out.write("							<li><a href=\"ionicons.html\">Ionicons Icons</a></li>\n");
      out.write("							<li><a href=\"themify.html\">Themify Icons</a></li>\n");
      out.write("							<li><a href=\"custom-icon.html\">Custom Icons</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("-->					\n");
      out.write("					\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"highchart.html\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-analytics-21\"></span><span class=\"mtext\">매출관리</span>\n");
      out.write("						</a>\n");
      out.write("						\n");
      out.write("<!-- 				\n");
      out.write("					</li>\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\n");
      out.write("							<span class=\"micon dw dw-right-arrow1\"></span><span class=\"mtext\">login/forgot/reset</span>\n");
      out.write("						</a>\n");
      out.write("						<ul class=\"submenu\">\n");
      out.write("							<li><a href=\"video-player.html\">Video Player</a></li>\n");
      out.write("							<li><a href=\"login.html\">Login</a></li>\n");
      out.write("							<li><a href=\"forgot-password.html\">Forgot Password</a></li>\n");
      out.write("							<li><a href=\"reset-password.html\">Reset Password</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write(" -->					\n");
      out.write("\n");
      out.write(" <!--  \n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\n");
      out.write("							<span class=\"micon dw dw-copy\"></span><span class=\"mtext\">Extra Pages</span>\n");
      out.write("						</a>\n");
      out.write("						-->\n");
      out.write("			<!--\n");
      out.write("						<ul class=\"submenu\">\n");
      out.write("							<li><a href=\"blank.html\">Blank</a></li>\n");
      out.write("							<li><a href=\"contact-directory.html\">Contact Directory</a></li>\n");
      out.write("							<li><a href=\"blog.html\">Blog</a></li>\n");
      out.write("							<li><a href=\"blog-detail.html\">Blog Detail</a></li>\n");
      out.write("							<li><a href=\"product.html\">Product</a></li>\n");
      out.write("							<li><a href=\"product-detail.html\">Product Detail</a></li>\n");
      out.write("							<li><a href=\"faq.html\">FAQ</a></li>\n");
      out.write("							<li><a href=\"profile.html\">Profile</a></li>\n");
      out.write("							<li><a href=\"gallery.html\">Gallery</a></li>\n");
      out.write("							<li><a href=\"pricing-table.html\">Pricing Tables</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					\n");
      out.write(" -->\n");
      out.write(" \n");
      out.write(" <!--  					\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"javascript:;\" class=\"dropdown-toggle\">\n");
      out.write("							<span class=\"micon dw dw-list3\"></span><span class=\"mtext\">Multi Level Menu</span>\n");
      out.write("						</a>\n");
      out.write("						<ul class=\"submenu\">\n");
      out.write("							<li><a href=\"javascript:;\">Level 1</a></li>\n");
      out.write("							<li><a href=\"javascript:;\">Level 1</a></li>\n");
      out.write("							<li><a href=\"javascript:;\">Level 1</a></li>\n");
      out.write("							<li class=\"dropdown\">\n");
      out.write("								<a href=\"javascript:;\" class=\"dropdown-toggle\">\n");
      out.write("									<span class=\"micon fa fa-plug\"></span><span class=\"mtext\">Level 2</span>\n");
      out.write("								</a>\n");
      out.write("								<ul class=\"submenu child\">\n");
      out.write("									<li><a href=\"javascript:;\">Level 2</a></li>\n");
      out.write("									<li><a href=\"javascript:;\">Level 2</a></li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li><a href=\"javascript:;\">Level 1</a></li>\n");
      out.write("							<li><a href=\"javascript:;\">Level 1</a></li>\n");
      out.write("							<li><a href=\"javascript:;\">Level 1</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					\n");
      out.write("	-->				\n");
      out.write("					<li>\n");
      out.write("						<a href=\"sitemap.html\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-diagram\"></span><span class=\"mtext\">페이지 바로가기</span>\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("<!--  				\n");
      out.write("					<li>\n");
      out.write("						<a href=\"chat.html\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-chat3\"></span><span class=\"mtext\">Chat</span>\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"invoice.html\" class=\"dropdown-toggle no-arrow\">\n");
      out.write("							<span class=\"micon dw dw-invoice\"></span><span class=\"mtext\">Invoice</span>\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("-->						\n");
      out.write("					<li>\n");
      out.write("						<div class=\"dropdown-divider\"></div>\n");
      out.write("					</li>\n");
      out.write("				\n");
      out.write("				\n");
      out.write("					\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<div class=\"mobile-menu-overlay\"></div>\n");
      out.write("\n");
      out.write("<!-- ----------------------------------------------------------------------------------------------------------------- -->\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"main-container\">\n");
      out.write("		<div class=\"pd-ltr-20 xs-pd-20-10\">\n");
      out.write("			<div class=\"min-height-200px\">\n");
      out.write("				<div class=\"page-header\">\n");
      out.write("					<div class=\"row\">\n");
      out.write("						<div class=\"col-md-6 col-sm-12\">\n");
      out.write("							<div class=\"title\">\n");
      out.write("								<h4>상품관리</h4>\n");
      out.write("							</div>\n");
      out.write("							<!--  \n");
      out.write("							<nav aria-label=\"breadcrumb\" role=\"navigation\">\n");
      out.write("								<ol class=\"breadcrumb\">\n");
      out.write("									<li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\n");
      out.write("									<li class=\"breadcrumb-item active\" aria-current=\"page\">DataTable</li>\n");
      out.write("								</ol>\n");
      out.write("							</nav>\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write(" 	-->			\n");
      out.write("<!-- ----------------------------------------------------------------------------------------------------------------- -->				\n");
      out.write("				\n");
      out.write("			\n");
      out.write("				<!-- Checkbox select Datatable End -->\n");
      out.write("				<!-- Export Datatable start -->\n");
      out.write("				<div class=\"card-box mb-30\">\n");
      out.write("				\n");
      out.write("	\n");
      out.write("					<div class=\"pd-20\">\n");
      out.write("						<h4 class=\"text-blue h4\">상품 관리 모드</h4>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("				\n");
      out.write("					<form method=\"post\" action=\"productInsert.do\" enctype=\"multipart/form-data\">\n");
      out.write("					\n");
      out.write("					<input type=\"submit\" value=\"등록\"/>\n");
      out.write("					\n");
      out.write("					<div class=\"pb-20\">\n");
      out.write("					\n");
      out.write("								\n");
      out.write("						<table class=\"checkbox-datatable table nowrap\">\n");
      out.write("							\n");
      out.write("							\n");
      out.write("									\n");
      out.write("									\n");
      out.write("									<tr><th class=\"table-plus datatable-nosort\"></th></tr>\n");
      out.write("									\n");
      out.write("									<tr>\n");
      out.write("									<th>카테고리 번호</th>\n");
      out.write("									<td><input type=\"text\" name=\"category_num\" value=\"\"/></td>\n");
      out.write("									</tr>\n");
      out.write("									\n");
      out.write("									\n");
      out.write("									<tr><th>상품이름</th> <td><input type=\"text\" name=\"product_name\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>상품정보</th> <td><input type=\"text\" name=\"product_info\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>상품이미지</th> <td><input type=\"file\" name=\"file\" multiple=\"multiple\"/></td></tr>\n");
      out.write("									<tr><th>판매가격</th> <td><input type=\"text\" name=\"sale_price\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>현재가격</th> <td><input type=\"text\" name=\"now_price\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>입고가</th> <td><input type=\"text\" name=\"in_price\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>재고</th> <td><input type=\"text\" name=\"stock\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>조회수</th> <td><input type=\"text\" name=\"product_view\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>배송번호</th> <td><input type=\"text\" name=\"delivery_num\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>소포장</th><td><input type=\"text\" name=\"smallpack\" value=\"\"/></td></tr>\n");
      out.write("									<tr><th>상품태그</th><td><input type=\"text\" name=\"product_tag\" value=\"\"/></td></tr>\n");
      out.write("								\n");
      out.write("					\n");
      out.write("							\n");
      out.write("								\n");
      out.write("								<!-- 	<td class=\"table-plus\"></td>  -->\n");
      out.write("									\n");
      out.write("									\n");
      out.write("	\n");
      out.write("									\n");
      out.write("									\n");
      out.write("								\n");
      out.write("						</table>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("				</form>\n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			<!-- href=\"productUpdate.do?product_num=\" \n");
      out.write("			x<td><input type=\"text\" value=\"\"/></td>-->	\n");
      out.write("				\n");
      out.write("				\n");
      out.write("			\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				<!-- Export Datatable End -->\n");
      out.write("			</div>\n");
      out.write("			<div class=\"footer-wrap pd-20 mb-20 card-box\">\n");
      out.write("				[  LittlePick  ]  made by  조다운, 이혜미, 조영주, 김준호\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- js -->\n");
      out.write("	<script src=\"resources/admin/resources/vendors/scripts/core.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/vendors/scripts/script.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/vendors/scripts/process.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/vendors/scripts/layout-settings.js\"></script>\n");
      out.write("	<script src=\"src/plugins/datatables/js/jquery.dataTables.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/dataTables.bootstrap4.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/dataTables.responsive.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/responsive.bootstrap4.min.js\"></script>\n");
      out.write("	<!-- buttons for Export datatable -->\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/dataTables.buttons.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/buttons.bootstrap4.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/buttons.print.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/buttons.html5.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/buttons.flash.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/pdfmake.min.js\"></script>\n");
      out.write("	<script src=\"resources/admin/resources/plugins/datatables/js/vfs_fonts.js\"></script>\n");
      out.write("	<!-- Datatable Setting js -->\n");
      out.write("	<script src=\"resources/admin/resources/vendors/scripts/datatable-setting.js\"></script></body>\n");
      out.write("</html></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
