/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-07-29 11:25:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _1_005fregister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-1.7.1.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style_daun.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#FFFFFF\">\r\n");
      out.write("<div class=\"register\">\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\" action=\"userInsert_save.do\" class=\"table2\">\r\n");
      out.write("<div class=\"register-logo\">\r\n");
      out.write("<a href=\"#\"><img src=\"resources/img/logo.png\" width=\"200px\"/></a>\r\n");
      out.write("</div>\r\n");
      out.write("     <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_name\" type=\"text\" class=\"normal\" placeholder=\"이름\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("     <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_email\" type=\"text\" class=\"normal\" placeholder=\"이메일\">\r\n");
      out.write("        <span id=\"idCheckResult\" style=\"width:150px;color:red\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_password\" type=\"password\" class=\"normal\" placeholder=\"비밀번호\">\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("        <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_password2\" type=\"password\" class=\"normal\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_nickname\" type=\"text\" class=\"normal\" placeholder=\"닉네임\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("      <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_phone\" type=\"text\" class=\"normal\" placeholder=\"전화번호\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("      <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_address\" type=\"text\" class=\"normal\" placeholder=\"주소\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("        <input name=\"user_birth\" type=\"text\" class=\"normal\" placeholder=\"생년월일  yyyy-mm-dd\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"normalbold tb_ttl\"  align=\"center\">\r\n");
      out.write("     <input type=\"radio\" name=\"user_gender\" id=\"user_gender\"\r\n");
      out.write("        value='M' />남성<input type=\"radio\" \r\n");
      out.write("        name=\"user_gender\" id=\"user_gender\" value='F' />여성\r\n");
      out.write("      </div> \r\n");
      out.write(" \r\n");
      out.write("          <div align=\"center\"> \r\n");
      out.write("        	\r\n");
      out.write("          <input type=\"submit\" class=\"confirm\"  value=\"가입하기\">\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"daun-sub\">\r\n");
      out.write("        <a href=\"1_login.do\">로그인</a>\r\n");
      out.write("        <p>-----------</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("</form>\r\n");
      out.write(" 		\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
